:ruby_command: "ruby"
:gem_command: "gem"
:gem_dir: "./gem_home"
:gem_bin_dir: "./gem_bin"
:data_dir: "./data"
:db_path: "./ruby-station.db"
:gem_install_option: "--no-rdoc --no-ri"
:server_port: 2534
:debug: false
